[versions]
minecraft           = "26.1.1"
fabric-loader       = "0.18.4"
parchment           = "1.21.10:2025.10.12"
fabric-api          = "0.145.3+26.1.1"
fabric-kotlin       = "1.13.9+kotlin.2.3.10"
polymer             = "0.16.0+26.1.1"
sgui                = "2.0.0+26.1"
server-translations = "3.0.1+26.1"
replay-studio       = "ca00f8101b"
permissions         = "0.7.0"

# Compatability
carpet        = "26.1-beta-9"
voicechat     = "fabric-2.6.12+26.1"
voicechat-api = "2.6.0"
vmp           = "0.2.0+beta.7.230+26.1"
c2me          = "0.3.7+alpha.0.59+26.1"

# Testing
reflections = "0.10.2"

# Plugins
fabric-loom = "1.15-SNAPSHOT"
spotless    = "8.1.0"
shadow      = "9.3.0"
explosion   = "0.3.1"

[libraries]
minecraft              = { module = "com.mojang:minecraft"                 , version.ref = "minecraft" }
fabric-loader          = { module = "net.fabricmc:fabric-loader"           , version.ref = "fabric-loader" }
fabric-api             = { module = "net.fabricmc.fabric-api:fabric-api"   , version.ref = "fabric-api" }
fabric-kotlin          = { module = "net.fabricmc:fabric-language-kotlin"  , version.ref = "fabric-kotlin" }
polymer-core           = { module = "eu.pb4:polymer-core"                  , version.ref = "polymer" }
polymer-blocks         = { module = "eu.pb4:polymer-blocks"                , version.ref = "polymer" }
polymer-resource-pack  = { module = "eu.pb4:polymer-resource-pack"         , version.ref = "polymer" }
sgui                   = { module = "eu.pb4:sgui"                          , version.ref = "sgui" }
server-translations    = { module = "xyz.nucleoid:server-translations-api" , version.ref = "server-translations" }
replay-studio          = { module = "com.github.ReplayMod:ReplayStudio"    , version.ref = "replay-studio" }
permissions            = { module = "me.lucko:fabric-permissions-api"      , version.ref = "permissions" }

# Compatability
carpet        = { module = "com.github.gnembon:fabric-carpet"    , version.ref = "carpet" }
voicechat     = { module = "maven.modrinth:simple-voice-chat"    , version.ref = "voicechat" }
voicechat-api = { module = "de.maxhenkel.voicechat:voicechat-api", version.ref = "voicechat-api" }
vmp           = { module = "maven.modrinth:vmp-fabric"           , version.ref = "vmp" }
c2me          = { module = "maven.modrinth:c2me-fabric"          , version.ref = "c2me" }

# Testing
reflections = { module = "org.reflections:reflections", version.ref = "reflections" }

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric-loom" }
spotless    = { id = "com.diffplug.spotless"   , version.ref = "spotless" }
shadow      = { id = "com.gradleup.shadow"     , version.ref = "shadow" }
explosion   = { id = "lol.bai.explosion"       , version.ref = "explosion"}