[versions]
minecraft           = "26.2"
fabric-loader       = "0.19.3"
fabric-api          = "0.152.1+26.2"
fabric-kotlin       = "1.13.12+kotlin.2.4.0"
polymer             = "0.17.0+26.2-rc-2"
sgui                = "2.1.0+26.2"
server-translations = "3.1.0+26.2"
replay-studio       = "ca00f8101b"

# Compatability
carpet        = "26.2"
voicechat     = "fabric-2.6.18+26.2"
voicechat-api = "2.6.13"
vmp           = "0.2.0+beta.7.235+26.2-rc-2"
c2me          = "0.4.1-alpha.0.3+26.2"

# Testing
reflections = "0.10.2"

# Plugins
fabric-loom = "1.17-SNAPSHOT"
spotless    = "8.7.0"
shadow      = "9.4.2"
explosion   = "0.3.1"

[libraries]
minecraft              = { module = "com.mojang:minecraft"                 , version.ref = "minecraft" }
fabric-loader          = { module = "net.fabricmc:fabric-loader"           , version.ref = "fabric-loader" }
fabric-api             = { module = "net.fabricmc.fabric-api:fabric-api"   , version.ref = "fabric-api" }
fabric-kotlin          = { module = "net.fabricmc:fabric-language-kotlin"  , version.ref = "fabric-kotlin" }
polymer-core           = { module = "eu.pb4:polymer-core"                  , version.ref = "polymer" }
polymer-resource-pack  = { module = "eu.pb4:polymer-resource-pack"         , version.ref = "polymer" }
sgui                   = { module = "eu.pb4:sgui"                          , version.ref = "sgui" }
server-translations    = { module = "xyz.nucleoid:server-translations-api" , version.ref = "server-translations" }
replay-studio          = { module = "com.github.ReplayMod:ReplayStudio"    , version.ref = "replay-studio" }

# Compatability
carpet        = { module = "com.github.gnembon:fabric-carpet"    , version.ref = "carpet" }
voicechat     = { module = "maven.modrinth:simple-voice-chat"    , version.ref = "voicechat" }
voicechat-api = { module = "de.maxhenkel.voicechat:voicechat-api", version.ref = "voicechat-api" }
vmp           = { module = "maven.modrinth:vmp-fabric"           , version.ref = "vmp" }
c2me          = { module = "maven.modrinth:c2me-fabric"          , version.ref = "c2me" }

# Testing
reflections = { module = "org.reflections:reflections", version.ref = "reflections" }

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric-loom" }
spotless    = { id = "com.diffplug.spotless"   , version.ref = "spotless" }
shadow      = { id = "com.gradleup.shadow"     , version.ref = "shadow" }
explosion   = { id = "lol.bai.explosion"       , version.ref = "explosion"}