[versions]
minecraft           = "1.21.9"
fabric-loader       = "0.17.2"
parchment           = "1.21.8:2025.09.14"
fabric-api          = "0.133.10+1.21.9"
fabric-kotlin       = "1.13.5+kotlin.2.2.10"
polymer             = "0.14.0-beta.1+1.21.9-pre1"
sgui                = "1.11.0-rc.1+1.21.9"
server-translations = "2.5.2+1.21.9-pre3"
inject              = "3.1.4"
debug-tools-api     = "1.0.17"
replay-studio       = "03d5609f77"
permissions         = "0.5.0"

# Compatability
carpet        = "1.4.185"
voicechat     = "fabric-1.21.9-pre3-2.6.4"
voicechat-api = "2.6.0"
vmp           = "0.2.0+beta.7.210+1.21.9-pre1"
c2me          = "0.3.5+alpha.0.28+1.21.9-pre3"

# Plugins
fabric-loom = "1.11-SNAPSHOT"
spotless    = "7.1.0"
shadow      = "8.3.5"
explosion   = "0.3.1"

[libraries]
minecraft              = { module = "com.mojang:minecraft"                 , version.ref = "minecraft" }
fabric-loader          = { module = "net.fabricmc:fabric-loader"           , version.ref = "fabric-loader" }
fabric-api             = { module = "net.fabricmc.fabric-api:fabric-api"   , version.ref = "fabric-api" }
fabric-kotlin          = { module = "net.fabricmc:fabric-language-kotlin"  , version.ref = "fabric-kotlin" }
polymer-core           = { module = "eu.pb4:polymer-core"                  , version.ref = "polymer" }
polymer-blocks         = { module = "eu.pb4:polymer-blocks"                , version.ref = "polymer" }
polymer-resource-pack  = { module = "eu.pb4:polymer-resource-pack"         , version.ref = "polymer" }
polymer-virtual-entity = { module = "eu.pb4:polymer-virtual-entity"        , version.ref = "polymer" }
sgui                   = { module = "eu.pb4:sgui"                          , version.ref = "sgui" }
server-translations    = { module = "xyz.nucleoid:server-translations-api" , version.ref = "server-translations" }
debug-tools-api        = { module = "me.senseiwells:debug-tools-api"       , version.ref = "debug-tools-api" }
replay-studio          = { module = "com.github.ReplayMod:ReplayStudio"    , version.ref = "replay-studio" }
permissions            = { module = "me.lucko:fabric-permissions-api"      , version.ref = "permissions" }

inject-api             = { module = "net.mcbrawls.inject:api"             , version.ref = "inject" }
inject-http            = { module = "net.mcbrawls.inject:http"            , version.ref = "inject" }
inject-fabric          = { module = "net.mcbrawls.inject:fabric"          , version.ref = "inject" }

# Compatability
carpet        = { module = "com.github.gnembon:fabric-carpet"    , version.ref = "carpet" }
voicechat     = { module = "maven.modrinth:simple-voice-chat"    , version.ref = "voicechat" }
voicechat-api = { module = "de.maxhenkel.voicechat:voicechat-api", version.ref = "voicechat-api" }
vmp           = { module = "maven.modrinth:vmp-fabric"           , version.ref = "vmp" }
c2me          = { module = "maven.modrinth:c2me-fabric"          , version.ref = "c2me" }

[plugins]
fabric-loom = { id = "fabric-loom"          , version.ref = "fabric-loom" }
spotless    = { id = "com.diffplug.spotless", version.ref = "spotless" }
shadow      = { id = "com.gradleup.shadow"  , version.ref = "shadow" }
explosion   = { id = "lol.bai.explosion"    , version.ref = "explosion"}